msotly there

diff --git a/knight b/knight
--- a/knight
+++ b/knight
@@ -99,7 +99,7 @@ to_str () case $1 in
 	N)     Reply= ;;
 	A*)    eval "to_str \$$1" ;;
 	a*)    ary_join "$NEWLINE" "$1" ;;
-	[fF]*) run "$1"; to_str "$Reply" ;;
+	[fFv]*) run "$1"; to_str "$Reply" ;;
 	*) die "unknown type for to_str: $1" ;;
 esac
 
@@ -116,12 +116,12 @@ to_int () case $1 in
 	A*)   eval "to_int \$$1" ;;
 	a*)   Reply=${1#a}
 	      Reply=${Reply%%"$ARY_SEP"*} ;;
-	[fF]*) run "$1"; to_int "$Reply" ;;
+	[fFv]*) run "$1"; to_int "$Reply" ;;
 	*) die "unknown type for to_int: $1" ;;
 esac
 
 ## Returns 0 if its argument is truthy
-to_bool () case $1 in [sFN]|[ia]0) false; esac
+to_bool () case $1 in [sFN]|[ia]0) false;; [fFv]*) run "$1"; to_bool "$Reply"; esac
 
 # Converts its argument to an array, storing the result in $Reply
 to_ary () case $1 in
@@ -135,7 +135,7 @@ to_ary () case $1 in
 		done ;;
 	A*)    eval "to_ary \$$1" ;;
 	a*)    Reply=$1 ;;
-	[fF]*) run "$1"; to_ary "$Reply" ;;
+	[fFv]*) run "$1"; to_ary "$Reply" ;;
 	*) die "unknown type for $0: $1" ;;
 esac
 
@@ -170,7 +170,7 @@ s/^/"/; s/x$/"/' ;;
 		printf \]
 		;;
 	A*) eval "dump \$$1" ;;
-	[fF]*) printf '[%s]' "$1" ;;
+	[fFv]*) printf '[%s]' "$1" ;;
 	*) die "unknown type for dump: $1" ;;
 esac
 
@@ -317,7 +317,7 @@ next_expr () {
 				Line=${Line}${NEWLINE}${_tmp}
 			done
 			Reply=s${Line%%"$_quote"*}
-			Line=${Line#"$Reply"} ;;
+			Line=${Line#"${Reply#s}$_quote"} ;;
 
 		# Functions
 		[][TFNPRBCQDOLAWIGSE\$\+\*\/\%\^\<\>\?\&\|\;\~\!\=\,-]*)
@@ -340,17 +340,22 @@ next_expr () {
 	esac
 }
 
-## Evaluates the first arg as a knight program, putting the result in $REPLY.
+## Evaluates the first arg as a knight program, putting the result in $Reply.
 eval_kn () {
-	next_expr <<EOS || die 'no program given'
+	# TODO: `exec` with no args to make this a builtin?
+	if [ $# = 0 ]; then
+		next_expr
+	else
+		next_expr <<EOS
 $1
 EOS
+	fi || die 'no program given'
 	run "$Reply"
 }
 
 run () {
 	case $1 in
-		v*) eval "\$$1"; return ;; # `set -o nounset` will fail if the var isnt valid
+		v*) eval "run \$$1"; return ;; # `set -o nounset` will fail if the var isnt valid
 		F?*) eval "run \"\$$1\""; return ;;
 		[!f]*) Reply="$1"; return ;;
 	esac
@@ -359,121 +364,98 @@ run () {
 	_old_IFS=$IFS; IFS=$FN_SEP && set -o noglob
 	set -- $1 && IFS=$_old_IFS && set +o noglob
 
-	_fn=${1#f}; shift
-	case $_fn in
+	local fn=${1#f}; shift # Fn can be `_fn`
+
+	# Execute functions
+	case $fn in
 		# Arity 1
-		R) TODO "$_fn" ;;
-		P) TODO "$_fn" ;;
+		R) TODO "$fn" ;;
+		P) TODO "$fn" ;;
 
 		# Arity 2
 		B) Reply=$1 ;;
 		C) run "$1"; run "$Reply" ;;
 		Q) to_int "$1"; exit $Reply ;;
 		D) run "$1"; set -- "$Reply"; dump "$1"; Reply="$1" ;;
-		O) TODO "$_fn" ;;
-		L) TODO "$_fn" ;;
+		O) if to_str "$1"; [ "${Reply%\\}" = "$Reply" ]; then
+				printf '%s\n' "$Reply"
+			else
+				printf '%s' "${Reply%?}"
+			fi
+			Reply=N ;;
+		L) TODO "$fn" ;;
 		!) ! to_bool "$1"; newbool ;;
 		\~) to_int "$1"; Reply=i$(( - Reply )) ;;
-		A) TODO "$_fn" ;;
+		A) run "$1"; case $Reply in
+			s*) Reply=i$(printf %d \'"$Reply") ;;
+			i*) TODO ;; #printf '%b\n' '\060' octal ew
+			esac ;;
 		,) run "$1" ; new_ary "$Reply" ;;
 		\[) run "$1"
 			case $Reply in
 				s*) Reply=s$(printf %c "$Reply") ;;
-				[aA]*) TODO "$_fn for arrays" ;;
+				[aA]*) TODO "$fn for arrays" ;;
 			esac ;;
 		\]) run "$1"
 			case $Reply in
 				s*) Reply=s${Reply#s?} ;;
-				[aA]*) TODO "$_fn for arrays" ;;
+				[aA]*) TODO "$fn for arrays" ;;
 			esac ;;
+		E) to_str "$1"; eval_kn "$Reply" ;;
+		\$) to_str "$1"; Reply=s$( $Reply ) ;;
 
-		# +)
-		=)  run "$2"; eval "$1=\$Reply" ;;
-		\&) run "$1"; to_bool "$Reply" && run "$2";;
-		\|) run "$1"; to_bool "$Reply" || run "$2";;
-		W)  while run "$1"; to_bool "$Reply"; do run "$2"; done; REPLY=N;;
-		I)  run "$1"; if to_bool "$Reply"; then run "$2"; else run "$3"; fi ;;
+		# Arity 2
+		\;) run "$1"; run "$2" ;;
+		+) run "$1"; set -- "$Reply" "$2"; case $1 in
+			i*) to_int "$2"; Reply=i$((${1#?} + Reply)) ;;
+			s*) to_str "$2"; Reply=s${1#?}$Reply ;;
+			[aA]*) TODO "$fn for arrays" ;;
+			*)  die "unknown argument to $fn: $1" ;;
+			esac ;;
+		-) run "$1"; set -- "$Reply" "$2"; to_int "$2"; Reply=i$((${1#?} - Reply)) ;;
+		\*) run "$1"; set -- "$eply" "$2"; case $1 in
+			i*) to_int "$2"; Reply=i$((${1#?} + Reply)) ;;
+			s*) TODO "$fn for strings" ;;
+			[aA]*) TODO "$fn for arrays" ;;
+			*)  die "unknown argument to $fn: $1"
+			esac ;;
+		/) run "$1"; set -- "$Reply" "$2"; to_int "$2"; Reply=i$((${1#?} / Reply)) ;;
+		%) run "$1"; set -- "$Reply" "$2"; to_int "$2"; Reply=i$((${1#?} % Reply)) ;;
+		^) run "$1"; set -- "$Reply" "$2"; case "$1" in
+			i*) to_int "$2"; Reply=i$(echo "${1#?} ^ $Reply" | bc) ;; # no exponents in posix
+			[aA]*) TODO "$fn for arrays" ;;
+			*)  die "unknown argument to $fn: $1"
+			esac ;;
+		\?) run "$1"; set --  "$Reply" "$2"; run "$2"; are_equal "$1" "$Reply"; newbool ;;
+		\<) run "$1"; compare "$Reply" "$2"; [ $Reply -lt 0 ]; newbool ;;
+		\>) run "$1"; compare "$Reply" "$2"; [ $Reply -gt 0 ]; newbool ;;
+
+		G) TODO "$fn" ;;
+		S) TODO "$fn" ;;
+
+		=)  run "$2"; eval "$1=\$Reply" ; ;;
+		\&) run "$1"; to_bool "$Reply" && run "$2"; ;;
+		\|) run "$1"; to_bool "$Reply" || run "$2"; ;;
+		W)  while run "$1"; to_bool "$Reply"; do run "$2"; done; Reply=N; ;;
+		I)  run "$1"; if to_bool "$Reply"; then run "$2"; else run "$3"; fi ; ;;
+		*) die 'unknown function: %s' "$1" ;;
 	esac
 }
 
 
-next_expr <<EOS
-D , ! F
+eval_kn <<'EOS'
+O ^ 9 3
 EOS
-run 'f,(a2:i1:i2'
-echo "$Reply"
-echo
+run "$Reply"
 
 exit
-## Executes a value, and put its result in $REPLY
+## Executes a value, and put its result in $Reply
 function run {
 	## Execute the remaining functions
-	case $fn in
-		# ARITY 1
-		C) run $1 ;;
-		E) to_str $1; eval_kn $REPLY ;;
-		\~) to_int $1; REPLY=i$((-REPLY)) ;;
-		\$) to_str $1; REPLY=s$($=REPLY) ;;
-		\!) ! to_bool $1; newbool ;;
-		Q) to_int $1; exit $REPLY ;;
-		L) # (technically only the * case is needed, but this speeds it up)
-			case $1 in
-			s*) REPLY=i${#1#s} ;;
-			a*) REPLY=i$arrays[$1] ;; 
-			*)  to_ary $1; REPLY=i$#reply ;;
-			esac ;;
-		D) dump $1; REPLY=$1 ;;
-		O) if to_str $1; [[ ${REPLY: -1} = \\ ]] # Needs a space so it's not `:-`
-			then print -rn -- ${REPLY%?}
-			else print -r  -- $REPLY
-			fi
-			REPLY=N ;;
-		,) new_ary $1 ;;
-		A) case $1 in
-			s*) 1=${1#s}; REPLY=i$(( #1 )) ;;
-			i*) REPLY=s${(#)1#i} ;;
-			*)  die "unknown argument to $fn: $1" ;;
-			esac ;;
-		\[) to_ary $1; REPLY=$reply[1] ;;
-		\]) case $1 in
-			s*) REPLY=s${1:2} ;;
-			*)  to_ary $1; shift reply; new_ary $reply ;;
-			esac ;;
-
-		# ARITY 2
-		\;) REPLY=$2 ;;
-		+) case $1 in
-			i*) to_int $2; REPLY=i$((${1#?} + REPLY)) ;;
-			s*) to_str $2; REPLY=s${1#?}$REPLY ;;
-			a*) to_ary $1; local old=($reply); to_ary $2; new_ary $old $reply ;;
-			*)  die "unknown argument to $fn: $1" ;;
-			esac ;;
-		-) to_int $2; REPLY=i$((${1#?} - REPLY)) ;;
-		\*) case $1 in
-			i*) to_int $2; REPLY=i$((${1#?} * REPLY)) ;;
-			s*) to_int $2; 1=${1#s}; REPLY=s${(pl:$((${#1} * REPLY))::$1:)} ;;
-			a*) to_ary $1; to_int $2; local -a ary
-				for (( i = 0; i < REPLY; i++ )); do
-					ary+=($reply)
-				done
-				new_ary $ary ;;
-			*) die "unknown argument to $fn: $1" ;;
-			esac ;;
-		/) to_int $2; REPLY=i$((${1#?} / REPLY)) ;;
-		%) to_int $2; REPLY=i$((${1#?} % REPLY)) ;;
-		\^) case $1 in
-			i*) to_int $2; REPLY=i$((${1#?} ** REPLY)) ;;
-			a*) to_str $2; ary_join "$REPLY" $1; REPLY=s$REPLY ;;
-			*)  die "unknown argument to $fn: $1" ;;
-			esac ;;
-		\?) are_equal $1 $2; newbool ;;
-		\<) compare $1 $2; (( REPLY < 0 )); newbool ;;
-		\>) compare $1 $2; (( REPLY > 0 )); newbool ;;
-
 		## Arity 3
 		G) case $1 in
 			s*) to_int $2
-				local start=$REPLY
+				local start=$Reply
 				to_int $3
 				REPLY=s${${1#s}:$start:$REPLY} ;;
 			a*) to_ary $1
